// The pet: a small sitting floppy-eared companion, as vector.
//
// The body is drawn twice under a left/right clip so each half takes a
// partner's colour -- the same "crossover split" technique
// CrossoverHeart.tsx uses for the app icon's motif, and the convention
// colors.ts documents: day-orange is your partner, night-blue is you.
//
// SYMMETRY ABOUT x=50 IS LOAD-BEARING, not tidiness. The body is clipped
// into halves at exactly that line, so any asymmetry hands one partner a
// visibly larger half. The path was generated by writing only the right
// half and reflecting it (x -> 100-x, with the curve chain walked
// backwards so control points swap), which is why every coordinate has an
// exact partner. petPaths.test.ts enforces it rather than trusting it.
//
// PET_BODY NEVER CHANGES BETWEEN MOODS -- only the eyes and mouth move. A
// mood that needed a different silhouette wouldn't be a mood, it'd be a
// second creature, and the split would have to be re-derived.
//
// Subpaths, in order: head/body mass, left ear, right ear, left paw, right
// paw. The ears and paws are separate closed subpaths rather than bumps in
// the outline -- that's what gives each its own stroke, and it's the whole
// difference between "floppy-eared pet" and "blob with lumps".
export const PET_BODY =
  'M50.0 23.8 C64.8 24.2 74.6 29.0 78.6 38.0 ' +
  'C82.0 45.4 83.2 54.4 82.6 64.0 C82.2 73.0 80.4 81.0 75.4 87.4 ' +
  'C71.0 92.4 61.6 94.0 55.6 93.0 C53.4 92.6 51.6 92.4 50.0 92.4 ' +
  'C48.4 92.4 46.6 92.6 44.4 93.0 C38.4 94.0 29.0 92.4 24.6 87.4 ' +
  'C19.6 81.0 17.8 73.0 17.4 64.0 C16.8 54.4 18.0 45.4 21.4 38.0 ' +
  'C25.4 29.0 35.2 24.2 50.0 23.8 Z M68.4 29.0 ' +
  'C77.6 24.4 90.6 28.4 92.4 41.0 C94.0 51.4 90.4 62.6 84.2 69.4 ' +
  'C79.6 74.0 73.6 71.8 73.0 65.0 C72.0 56.4 70.6 41.0 68.4 29.0 ' +
  'Z M31.6 29.0 C29.4 41.0 28.0 56.4 27.0 65.0 ' +
  'C26.4 71.8 20.4 74.0 15.8 69.4 C9.6 62.6 6.0 51.4 7.6 41.0 ' +
  'C9.4 28.4 22.4 24.4 31.6 29.0 Z M59.4 85.2 ' +
  'C63.3 85.2 66.4 87.3 66.4 90.0 C66.4 92.7 63.3 94.8 59.4 94.8 ' +
  'C55.5 94.8 52.4 92.7 52.4 90.0 C52.4 87.3 55.5 85.2 59.4 85.2 ' +
  'Z M40.6 85.2 C44.5 85.2 47.6 87.3 47.6 90.0 ' +
  'C47.6 92.7 44.5 94.8 40.6 94.8 C36.7 94.8 33.6 92.7 33.6 90.0 ' +
  'C33.6 87.3 36.7 85.2 40.6 85.2 Z';

// Belly patch. Drawn between the body fill and its outline, so it reads as
// fur rather than a sticker, and centred so it crosses the split evenly.
export const PET_BELLY =
  'M50.0 70.0 C56.4 70.0 61.6 74.3 61.6 79.6 ' +
  'C61.6 84.9 56.4 89.2 50.0 89.2 C43.6 89.2 38.4 84.9 38.4 79.6 ' +
  'C38.4 74.3 43.6 70.0 50.0 70.0 Z';

// Eyes and mouth are strokes, not fills -- a few short paths per mood
// instead of five separate illustrations.
//
// `thriving` through `sleepy` read as waiting rather than suffering, which
// is the difference between "we got busy" and "you failed it".
//
// `withdrawn` frowns, at the user's explicit direction. Worth knowing if
// you're about to change it back or forward: the pet was chosen over a
// streak counter precisely because a streak resetting assigns blame, and a
// downturned mouth is the same message with a face on it -- shown on the
// days someone was busiest. The level mouth it replaced is one line away:
//   'M47.2 62.2 Q48.6 63.4 50.0 62.6 Q51.4 63.4 52.8 62.2'
// Decide it deliberately either way rather than inheriting it.
export const PET_EYES: Record<string, string> = {
  thriving: 'M39.8 49.4 Q43.2 44.8 46.6 49.4 M53.4 49.4 Q56.8 44.8 60.2 49.4',
  content:
    'M40.2 47.8 C40.2 45.5 41.5 43.8 43.2 43.8 C44.9 43.8 46.2 45.5 46.2 47.8 ' +
    'C46.2 50.1 44.9 51.8 43.2 51.8 C41.5 51.8 40.2 50.1 40.2 47.8 Z ' +
    'M53.8 47.8 C53.8 45.5 55.1 43.8 56.8 43.8 C58.5 43.8 59.8 45.5 59.8 47.8 ' +
    'C59.8 50.1 58.5 51.8 56.8 51.8 C55.1 51.8 53.8 50.1 53.8 47.8 Z',
  // heavy lids: an upper line with a smaller one tucked beneath it
  sleepy:
    'M39.6 47.0 Q43.2 44.8 46.8 47.0 M41.0 49.6 Q43.2 50.7 45.4 49.6 ' +
    'M53.2 47.0 Q56.8 44.8 60.4 47.0 M54.6 49.6 Q56.8 50.7 59.0 49.6',
  withdrawn: 'M39.8 48.6 Q43.2 51.1 46.6 48.6 M53.4 48.6 Q56.8 51.1 60.2 48.6',
};

export const PET_MOUTH: Record<string, string> = {
  thriving: 'M44.2 59.8 Q47.1 65.2 50.0 61.6 Q52.9 65.2 55.8 59.8',
  content: 'M45.6 60.8 Q47.8 63.8 50.0 61.4 Q52.2 63.8 54.4 60.8',
  sleepy: 'M46.6 61.6 Q48.3 63.6 50.0 62.2 Q51.7 63.6 53.4 61.6',
  withdrawn: 'M44.8 63.8 Q50.0 60.2 55.2 63.8',
};

// Was #554B66, an off-palette grey chosen for softness. It reached only
// 2.41:1 against the pet's own blue half, so half the face was failing --
// and CLAUDE.md locks the palette anyway. colors.ink gets 4.12 on blue and
// 8.95 on orange. Imported lazily by the component rather than referenced
// here, so this file stays pure path data.
export const PET_LINE = '#2E2A3D';

// Pause overlay, not a fifth mood. Pause is a status -- "we're travelling"
// -- so it sits on top of whatever mood is current rather than replacing
// it, and must never read as a worse state of wellbeing.
export const PET_SLEEP_MARK = 'M82.0 20.0 L91.0 20.0 L82.0 30.0 L91.0 30.0';
