// The pet: a sitting cat, as vector. Replaced the floppy-eared dog
// 2026-09-23 at the user's request; moods, colours and the split are
// unchanged.
//
// Each shape is drawn twice under a left/right clip so each half takes a
// partner's colour -- the same "crossover split" technique
// CrossoverHeart.tsx uses for the app icon's motif: day-orange is your
// partner, night-blue is you.
//
// SYMMETRY ABOUT x=50 IS LOAD-BEARING, not tidiness. The shapes are clipped
// into halves at exactly that line, so any asymmetry hands one partner a
// visibly larger half. Every path was generated by writing only the right
// half and reflecting it (x -> 100-x, with the curve chain walked backwards
// so control points swap), which is why every coordinate has an exact
// partner. petPaths.test.ts enforces it rather than trusting it. No tail for
// the same reason: a tail curls to one side.
//
// THE SILHOUETTE NEVER CHANGES BETWEEN MOODS -- only the eyes and mouth
// move. A mood that needed a different silhouette wouldn't be a mood, it'd
// be a second creature.
//
// Two layers rather than one outline: the body (with its two paws as
// separate closed subpaths) is drawn first, then the head over it. One
// combined path would stroke the body's top edge straight across the face.

// Body mass plus left and right paws.
export const PET_BODY =
  'M50.0 52.0 C58.4 52.0 66.0 53.6 70.4 59.2 C76.2 66.4 79.4 78.0 76.6 85.8 ' +
  'C74.0 92.2 64.2 93.4 50.0 93.4 C35.8 93.4 26.0 92.2 23.4 85.8 ' +
  'C20.6 78.0 23.8 66.4 29.6 59.2 C34.0 53.6 41.6 52.0 50.0 52.0 Z ' +
  'M59.6 85.6 C63.4 85.6 66.4 87.7 66.4 90.2 C66.4 92.7 63.4 94.8 59.6 94.8 ' +
  'C55.8 94.8 52.8 92.7 52.8 90.2 C52.8 87.7 55.8 85.6 59.6 85.6 Z ' +
  'M40.4 85.6 C44.2 85.6 47.2 87.7 47.2 90.2 C47.2 92.7 44.2 94.8 40.4 94.8 ' +
  'C36.6 94.8 33.6 92.7 33.6 90.2 C33.6 87.7 36.6 85.6 40.4 85.6 Z';

// Head with the two pointed ears as bumps in one outline -- as separate
// subpaths their outlines would cut across the top of the head.
export const PET_HEAD =
  'M50.0 24.2 C54.0 23.6 57.4 23.4 60.2 23.8 L72.4 9.8 ' +
  'C74.4 15.6 77.0 24.0 78.4 31.2 C81.6 36.4 82.8 43.6 81.2 50.4 ' +
  'C79.0 59.4 67.6 63.6 50.0 63.6 C32.4 63.6 21.0 59.4 18.8 50.4 ' +
  'C17.2 43.6 18.4 36.4 21.6 31.2 C23.0 24.0 25.6 15.6 27.6 9.8 ' +
  'L39.8 23.8 C42.6 23.4 46.0 23.6 50.0 24.2 Z';

// Inside of each ear, in the soft fill, no outline.
export const PET_INNER_EARS =
  'M63.2 24.4 L71.4 15.2 L75.2 28.8 Z M24.8 28.8 L28.6 15.2 L36.8 24.4 Z';

// Belly patch. Drawn between the body fill and its outline, so it reads as
// fur rather than a sticker, and centred so it crosses the split evenly.
export const PET_BELLY =
  'M50.0 69.2 C55.7 69.2 60.4 73.3 60.4 78.4 C60.4 83.5 55.7 87.6 50.0 87.6 ' +
  'C44.3 87.6 39.6 83.5 39.6 78.4 C39.6 73.3 44.3 69.2 50.0 69.2 Z';

// Filled nose, and whiskers stroked thinner than the face. Same in every
// mood.
export const PET_NOSE = 'M47.6 46.4 L52.4 46.4 L50.0 49.2 Z';
export const PET_WHISKERS =
  'M62.4 48.4 L76.0 46.4 M62.6 51.2 L76.0 52.6 ' +
  'M37.6 48.4 L24.0 46.4 M37.4 51.2 L24.0 52.6';

// Eyes and mouth are strokes, not fills -- a few short paths per mood
// instead of four separate illustrations. The mouths hang off the nose as
// a cat's "ω".
//
// `thriving` through `sleepy` read as waiting rather than suffering, which
// is the difference between "we got busy" and "you failed it".
//
// `withdrawn` frowns, at the user's explicit direction (carried over from
// the dog). Worth knowing if you're about to change it back or forward: the
// pet was chosen over a streak counter precisely because a streak resetting
// assigns blame, and a downturned mouth is the same message with a face on
// it -- shown on the days someone was busiest. Decide it deliberately
// either way rather than inheriting it.
export const PET_EYES: Record<string, string> = {
  thriving: 'M36.6 41.0 Q40.0 36.4 43.4 41.0 M56.6 41.0 Q60.0 36.4 63.4 41.0',
  content:
    'M37.0 39.8 C37.0 37.4 38.3 35.6 40.0 35.6 C41.7 35.6 43.0 37.4 43.0 39.8 ' +
    'C43.0 42.2 41.7 44.0 40.0 44.0 C38.3 44.0 37.0 42.2 37.0 39.8 Z ' +
    'M57.0 39.8 C57.0 37.4 58.3 35.6 60.0 35.6 C61.7 35.6 63.0 37.4 63.0 39.8 ' +
    'C63.0 42.2 61.7 44.0 60.0 44.0 C58.3 44.0 57.0 42.2 57.0 39.8 Z',
  // heavy lids: an upper line with a smaller one tucked beneath it
  sleepy:
    'M36.4 39.4 Q40.0 37.2 43.6 39.4 M37.8 42.0 Q40.0 43.1 42.2 42.0 ' +
    'M56.4 39.4 Q60.0 37.2 63.6 39.4 M57.8 42.0 Q60.0 43.1 62.2 42.0',
  withdrawn: 'M36.6 40.4 Q40.0 43.0 43.4 40.4 M56.6 40.4 Q60.0 43.0 63.4 40.4',
};

export const PET_MOUTH: Record<string, string> = {
  thriving:
    'M50.0 49.2 L50.0 51.0 M44.6 50.6 Q47.3 55.8 50.0 51.0 Q52.7 55.8 55.4 50.6',
  content:
    'M50.0 49.2 L50.0 51.0 M45.8 51.0 Q47.9 54.0 50.0 51.0 Q52.1 54.0 54.2 51.0',
  sleepy:
    'M50.0 49.2 L50.0 51.0 M46.8 51.6 Q48.4 53.2 50.0 51.0 Q51.6 53.2 53.2 51.6',
  withdrawn: 'M50.0 49.2 L50.0 51.0 M45.2 54.4 Q50.0 50.8 54.8 54.4',
};

// Was #554B66, an off-palette grey chosen for softness. It reached only
// 2.41:1 against the pet's own blue half, so half the face was failing --
// and CLAUDE.md locks the palette anyway. colors.ink gets 4.12 on blue and
// 8.95 on orange. Imported lazily by the component rather than referenced
// here, so this file stays pure path data.
export const PET_LINE = '#2E2A3D';

// Pause overlay, not a fifth mood. Pause is a status -- "we're travelling"
// -- so it sits on top of whatever mood is current rather than replacing
// it, and must never read as a worse state of wellbeing.
export const PET_SLEEP_MARK = 'M82.0 20.0 L91.0 20.0 L82.0 30.0 L91.0 30.0';
