import { PET_BODY, PET_BELLY } from './petPaths';

// The body is clipped into halves at exactly x=50 to colour each partner's
// side, so asymmetry hands one partner a visibly larger half -- and it would
// look like a drawing mistake rather than a bug. The path is generated by
// reflecting a right-half chain, so this guards the invariant that makes
// that generation valid, not the artwork itself.
function points(d: string): [number, number][] {
  const nums = (d.match(/-?\d+\.?\d*/g) ?? []).map(Number);
  const out: [number, number][] = [];
  for (let i = 0; i + 1 < nums.length; i += 2) out.push([nums[i], nums[i + 1]]);
  return out;
}

describe('pet geometry', () => {
  it.each([
    ['PET_BODY', PET_BODY],
    ['PET_BELLY', PET_BELLY],
  ])('%s is symmetric about x=50', (_name, d) => {
    const pts = points(d);
    // Guards against an empty or mangled path silently passing the
    // mirror check below, which is vacuously true for zero points.
    expect(pts.length).toBeGreaterThan(8);
    const key = (x: number, y: number) => `${x.toFixed(1)},${y.toFixed(1)}`;
    const seen = new Set(pts.map(([x, y]) => key(x, y)));
    const unmirrored = pts.filter(([x, y]) => !seen.has(key(100 - x, y)));
    expect(unmirrored).toEqual([]);
  });

  it('uses only absolute commands', () => {
    // Relative commands would silently break the reflection above, since a
    // mirrored relative delta is not the mirror of the point it lands on.
    expect(PET_BODY).not.toMatch(/[mcqlzsvhta]/);
  });
});
