import {
  PET_BODY,
  PET_BELLY,
  PET_HEAD,
  PET_INNER_EARS,
  PET_NOSE,
  PET_WHISKERS,
} from './petPaths';

// The body is clipped into halves at exactly x=50 to colour each partner's
// side, so asymmetry hands one partner a visibly larger half -- and it would
// look like a drawing mistake rather than a bug. The path is generated by
// reflecting a right-half chain, so this guards the invariant that makes
// that generation valid, not the artwork itself.
function points(d: string): [number, number][] {
  const nums = (d.match(/-?\d+\.?\d*/g) ?? []).map(Number);
  const out: [number, number][] = [];
  for (let i = 0; i + 1 < nums.length; i += 2) out.push([nums[i], nums[i + 1]]);
  return out;
}

const SHAPES = [
  // [name, path, minimum point count]
  ['PET_BODY', PET_BODY, 40],
  ['PET_HEAD', PET_HEAD, 24],
  ['PET_BELLY', PET_BELLY, 12],
  ['PET_INNER_EARS', PET_INNER_EARS, 6],
  ['PET_WHISKERS', PET_WHISKERS, 8],
  ['PET_NOSE', PET_NOSE, 3],
] as const;

describe('pet geometry', () => {
  it.each(SHAPES)('%s is symmetric about x=50', (_name, d, min) => {
    const pts = points(d);
    // Guards against an empty or mangled path silently passing the
    // mirror check below, which is vacuously true for zero points.
    expect(pts.length).toBeGreaterThanOrEqual(min);
    const key = (x: number, y: number) => `${x.toFixed(1)},${y.toFixed(1)}`;
    const seen = new Set(pts.map(([x, y]) => key(x, y)));
    const unmirrored = pts.filter(([x, y]) => !seen.has(key(100 - x, y)));
    expect(unmirrored).toEqual([]);
  });

  it('uses only absolute commands', () => {
    // Relative commands would silently break the reflection above, since a
    // mirrored relative delta is not the mirror of the point it lands on.
    // Same list as the symmetry check, so the two can't drift apart.
    for (const [, d] of SHAPES) {
      expect(d).not.toMatch(/[mcqlzsvhta]/);
    }
  });
});
